### ISSUE TITLE
Create Migration Table for Organization Table

### ISSUE THREAD

**Issue by Twincasper** [Team10MLS/TheLighthouse#16]

**Comment by Jl0p3z17** [comment]
Create Organizations Table:
The migration file should contain instructions to create the Organizations table with the specified columns.

Columns:

- id (Primary Key, Integer): This column serves as the primary key for the Organizations table, uniquely identifying each organization.
- name (String): This column stores the name of the organization. It should have a data type of string.

Constraints:
- Primary Key Constraint: The id column should be designated as the primary key of the Organizations table.
